site_url: https://adechlien.blog
publish_mode: editorial_workflow

backend:
  name: github
  repo: adechlien/Leggiamo
  branch: main
  base_url: https://adechlien.blog
  auth_endpoint: /api/auth

local_backend: false

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "texts"
    label: "Textos"
    label_singular: "Texto"
    folder: "src/content/texts"
    create: true
    slug: "{{uuid}}"

    preview_path: "/preview"

    fields:
      - { name: title, label: "TÃ­tulo", widget: string }

      - name: type
        label: Tipo
        widget: select
        default: lagrimas
        options:
          - lagrimas
          - colores
          - still
          - placebo
          - pintas

      - { name: heroImage, label: "Imagen principal", widget: image, required: false }

      - { name: pubDate, label: Fecha, widget: datetime, default: "{{now}}" }

      - { name: color, label: Color, widget: color, default: "#024350" }

      - { name: featured, label: "Destacado", widget: boolean, default: false }

      - { name: body, label: "Contenido", widget: markdown }
