site_url: https://adechlien.blog

backend:
  name: git-gateway
  branch: main

local_backend: false

media_folder: "public/portrait"
public_folder: "/portrait"

collections:
  - name: "texts"
    label: "Texts"
    folder: "src/content/texts"
    create: true
    identifier_field: title

    slug: "{{uuid}}"


    fields:
      - { name: title, label: Title, widget: string }

      - name: type
        label: Type
        widget: select
        default: pintas
        options:
          - lagrimas
          - colores
          - still
          - placebo
          - pintas

      - { name: heroImage, label: Hero, widget: image, required: false }

      - name: pubDate
        label: Date
        widget: datetime
        format: "MMM D YYYY"
        time_format: false

      - { name: color, label: Color, widget: color, default: "#44150A" }

      - { name: featured, label: Featured, widget: boolean, default: false }

      - { name: body, label: Body, widget: markdown }
